version: '3.7'
services:
  postgresql:
    image: postgres:alpine
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db-api
