version: '3.7'
services:
  postgres:
    image: postgres:14.0
    ports:
      - '8080:8080'
    volumes:
      - ./data:/var/lib/postgres
    environment:
      - POSTGRES_RANDOM_ROOT_PASSWORD=yes
      - POSTGRES_DATABASE=app_db
      - POSTGRES_USER=user_one
      - POSTGRES_PASSWORD=example
